import {
  faArrowLeft,
  faArrowRightFromBracket,
  faArrowsRotate,
  faBars,
  faBell,
  faBookOpen,
  faBoxesStacked,
  faChevronDown,
  faChevronRight,
  faDisplay,
  faDownload,
  faGear,
  faHouse,
  faLink,
  faMagnifyingGlass,
  faMoon,
  faPlus,
  faServer,
  faShieldHalved,
  faSitemap,
  faStore,
  faSun,
  faTerminal,
  faUsers,
  faXmark,
  faWandSparkles,
} from '@fortawesome/free-solid-svg-icons'

export const fontAwesomeIcons = {
  arrowLeft: faArrowLeft,
  arrowRightFromBracket: faArrowRightFromBracket,
  arrowsRotate: faArrowsRotate,
  bars: faBars,
  bell: faBell,
  bookOpen: faBookOpen,
  boxesStacked: faBoxesStacked,
  chevronDown: faChevronDown,
  chevronRight: faChevronRight,
  display: faDisplay,
  download: faDownload,
  gear: faGear,
  house: faHouse,
  link: faLink,
  magnifyingGlass: faMagnifyingGlass,
  moon: faMoon,
  plus: faPlus,
  server: faServer,
  shieldHalved: faShieldHalved,
  sitemap: faSitemap,
  sparkles: faWandSparkles,
  store: faStore,
  sun: faSun,
  terminal: faTerminal,
  users: faUsers,
  xmark: faXmark,
} as const

export type FontAwesomeIconName = keyof typeof fontAwesomeIcons
